### ISSUE TITLE
database issue 

### ISSUE THREAD

**Issue by vivek779** [thelfensdrfer/melone#1]
I have installed melone and it require database so i have created database  bt on the local host it is not showing templates and key on background it is showing error no such table do we putt all templates and entries in the table  is there your default database file  which i can use for testing purpose

**Comment by thelfensdrfer** [comment]
This is a great idea but I do not have the original database anymore. You have to take the column names and types from the models in the model directory. It would be great if you could create a pull request afterwards. If you do not have the time, tell me, I will do my best to restore the tables then.

**Comment by thelfensdrfer** [comment]
You simply have to copy the sql data from https://github.com/thelfensdrfer/melone/blob/master/components/Sql.js

**Comment by hemsinfotech** [comment]
i am also looking for database of melone for use for testing purpose.it you can restore the database that should be great.

**Comment by thelfensdrfer** [comment]
Like i wrote in the pull request: "To install the database you have to execute `node ./lib/install.js` with a [valid config file](https://github.com/thelfensdrfer/melone#config)."

Forgot that I already added a migration script for travis ci.

**Comment by vivek779** [comment]
Thanks it works now it
I have one more query where is smtp creditials file present so that i can set it and send mail for test purpose .
I tried bt not able to understand where it is and how do we set it to send mails and track it
